// @charset utf-8
import Vue from 'vue'
var payments=new Vue({
    data: {
        userName: 'tady',
        userPass: '123456',
        userLogo: require('../assets/money.jpg'),
        gridColumns:[],
        searchString: '',
        searchColumn: '',
        newBill:{
             id:0,
             type:'支出',
             date:(new Date()).toLocaleDateString(),
             name:'',
             moneys:0,
             categories:'',
             details:''	
        },
        bills:[
             {
             id:1,
             type:'收入',
             date:'2018-2-2',
             name:'五月份工资',
             moneys:5558,
             categories:'工资',
             details:'公积金已扣'
             },
             {
             id:2,
             type:'支出',
             date:'2018-3-3',
             name:'买菜',
             moneys:455,
             categories:'蔬菜/肉类',
             details:'青菜、排骨'
             },
             {
             id:3,
             type:'支出',
             date:'2018-1-31',
             name:'水果',
             moneys:300,
             categories:'水果/零食',
             details:'西瓜'
             },
             {
             id:4,
             type:'支出',
             date:'2018-4-4',
             name:'看电影',
             moneys:460,
             categories:'休闲娱乐',
             details:'电影票、小吃'
             },
             {
             id:5,
             type:'支出',
             date:'2018-5-5',
             name:'尚湖一日游',
             moneys:112,
             categories:'旅游',
             details:'门票、车票'
             },
             {
             id:6,
             type:'收入',
             date:'2018-6-6',
             name:'余额宝到账',
             moneys:500,
             categories:'理财',
             details:''
             },
             {
             id:7,
             type:'支出',
             date:'2018-7-7',
             name:'聚会',
             moneys:500,
             categories:'休闲娱乐',
             details:''
             },
             {
             id:8,
             type:'收入',
             date:'2018-8-8',
             name:'余额宝到账',
             moneys:1500,
             categories:'理财',
             details:''
             },
             {
             id:9,
             type:'支出',
             date:'2018-9-9',
             name:'旅游',
             moneys:3000,
             categories:'旅游',
             details:''
             },
             {
             id:10,
             type:'收入',
             date:'2018-10-1',
             name:'投资理财',
             moneys:5000,
             categories:'理财',
             details:''
             },
            {
             id:11,
             type:'支出',
             date:'2018-11-20',
             name:'投资失败',
             moneys:2500,
             categories:'理财',
             details:''
            },
             {
             id:12,
             type:'收入',
             date:'2018-12-12',
             name:'投资成功',
             moneys:4500,
             categories:'理财',
             details:''
             }
         ],
          incomes:[
             {
              pname:'工 资'
             },
             {
              pname:'理财'
             }
	    ],
         pays:[
             {
                pname:'外出吃饭'
             },
             {
                pname:'水果/零食'
             },
             {
                pname:'蔬菜/肉类'
             },
             {
                pname:'日用品'
             },
             {
                pname:'家用电器'
             },
             {
                pname:'服装'
            },
            {
                pname:'旅游'
            },
            {
                pname:'休闲娱乐'
            }
        ]
  }
})
export default payments
